config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  root 'home#index'
  resources :artists
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/artist.rb
class Artist < ApplicationRecord
    has_one_attached :cover
    # extend FriendlyId
    # friendly_id :one_link, use: :slugged
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/artists_controller.rb
class ArtistsController < ApplicationController
  before_action :set_artist, only: [:show, :edit, :update, :destroy]

  def index
    @artists = Artist.all
    end
  
    def new
      @artist = Artist.new
      render partial: 'form'
    end
  
    def show
    end
    
  
    def create
      @artist = Artist.new(artist_params)
        if @artist.save
          redirect_to artists_path
        else
          render :new  
        end  
    end
  
    def edit
      render partial: 'form'
    end
  
    def update

        if @artist.update(artist_params)
          redirect_to artist_path
        else
          render :edit
        end
    end
  
    def destroy
      @artist.destroy
      redirect_to artists_path
    end
  

    private
      def artist_params
        params.require(:artist).permit(:attr, :performer, :recordlabel, :cover, :facebook_num, :spotify_num, :youtube_num, :instagram_num, 
        :twitter_num, :dropbox_link, :video_emb, :biography, :audio, :booking, :spotify_link, :facebook_link, :instagram_link, :twitter_link, :youtube_link, :one_link)
      end

      def set_artist
        # @artist = Artist.find(params[:id])
        @artist = Artist.friendly.find(params[:id])
      end

end

app/controllers/english_landing_controller.rb
class EnglishLandingController < ApplicationController
  def index
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/artists_helper.rb
module ArtistsHelper
end

app/helpers/english_landing_helper.rb
module EnglishLandingHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/artists/_form.html.erb
<h1>Create a One-Sheet</h1>
<h1> <%= @artist.id ? 'Edit Chart' : 'Create Chart'%> </h1>

<%= form_for @artist do |f| %>
<div>
    <%= f.label :performer %>
    <%= f.text_field :performer %>
    </div> <br>

<div>    
    <%= f.label 'Record Label' %>
    <%= f.text_field :recordlabel %>
    </div> <br>

<div>    
    <%= f.label :cover %>
    <%= f.file_field :cover %>
    </div> <br>

<div>    
    <%= f.label :facebook_num %>
    <%= f.text_field :facebook_num %>
    </div> <br>

<div>    
    <%= f.label :spotify_num %>
    <%= f.text_field :spotify_num %>
    </div> <br>

<div>    
    <%= f.label :youtube_num %>
    <%= f.text_field :youtube_num %>
    </div> <br>

 <div>   
    <%= f.label :instagram_num %>
    <%= f.text_field :instagram_num %>
    </div> <br>

 <div>   
    <%= f.label :twitter_num %>
    <%= f.text_field :twitter_num %>
    </div> <br>

 <div>   
    <%= f.label :dropbox_link %>
    <%= f.text_field :dropbox_link %>
    </div> <br>

 <div>   
    <%= f.label 'Youtube Video ID' %>
    <%= f.text_field :video_emb %>
    </div> <br>

  <div>  
    <%= f.label :biography %>
    <%= f.text_area :biography %>
    </div> <br>

 <div>   
    <%= f.label :audio %>
    <%= f.text_field :audio %>
    </div> <br>
    
 <div>   
    <%= f.label :booking %>
    <%= f.text_field :booking %>
    </div> <br>

<div>
    <%= f.label :spotify_link %>
    <%= f.text_field :spotify_link %>
    </div> <br>

<div>
    <%= f.label :facebook_link %>
    <%= f.text_field :facebook_link %>
    </div> <br>

<div>
    <%= f.label :instagram_link %>
    <%= f.text_field :instagram_link %>
    </div> <br>

<div>
    <%= f.label :twitter_link %>
    <%= f.text_field :twitter_link %>
    </div> <br>

<div>
    <%= f.label :youtube_link %>
    <%= f.text_field :youtube_link %>
    </div> <br>

<div>
    <%= f.label :one_link %>
    <%= f.text_field :one_link %>
    </div> <br>

<div>
    <%= f.submit%>
    </div>
<% end%>


<hr>

<button>
<%= link_to 'Cancel', root_path%>
</button>

app/views/artists/edit.html.erb
<h1>Artists#edit</h1>
<p>Find me in app/views/artists/edit.html.erb</p>

app/views/artists/index.html.erb
<div class="artist-index">
<h1>Welcome Ricky, Artist One-Sheets Database</h1>

<ul>
<% @artists.each do |artist| %>
<li> <%= link_to artist.performer, artist %></li>
<% end %>
</ul>

<button class="btn btn-warning">
<%= link_to 'Create new sheet', new_artist_path %>
</button>

</div>

app/views/artists/new.html.erb
<h1>Artists#new</h1>
<p>Find me in app/views/artists/new.html.erb</p>

app/views/artists/show.html.erb
 <title>Lnza.me - <%= @artist.performer %></title>

    <div class="container-fluid maxx">

         <div class="mt-3 titleSec">
           <h1>ONE-SHEET</h1>
           <hr>
         </div>

         <!-- START 2 COLUMN -->
          <div class="row">
            <div class="col"></div>
            <div class="col-sm-12 col-md-5 col-lg-5">
              <div class="card" style="max-width: 20rem;">
                <!-- <img src="" class="card-img-top" alt="..."> -->
                <div class="card-body">
                  <h5 class="card-title artistName"> <%= @artist.performer %> </h5>
                  <p class="card-text lead"> <%= @artist.recordlabel %></p>
                  <div class="albumFeature"> <%= image_tag(@artist.cover) %> </div>
       
                </div>
                <!-- Facebook -->
                <div class="oneSocial facebook">
                 <div class="row">
                   <div class="col-4">
                      <i class="fab fa-facebook-f"></i>
                   </div>
                   <div class="col-8">
                     <h2 class="socialText"> <%= @artist.facebook_num %> </h2>
                   </div>
                 </div>
                  </div>

                     <!-- Spotify -->
                <div class="oneSocial spotify">
                    <div class="row">
                      <div class="col-4">
                         <i class="fab fa-spotify"></i>
                      </div>
                      <div class="col-8">
                        <h2 class="socialText"> <%= @artist.spotify_num %> </h2>
                      </div>
                    </div>
                     </div>


                     <!-- Youtube -->
                <div class="oneSocial youtube">
                    <div class="row">
                      <div class="col-4">
                         <i class="fab fa-youtube"></i>
                      </div>
                      <div class="col-8">
                        <h2 class="socialText"> <%= @artist.youtube_num %> </h2>
                      </div>
                    </div>
                     </div>

                            <!-- instagram -->
                <div class="oneSocial instagram">
                    <div class="row">
                      <div class="col-4">
                         <i class="fab fa-instagram"></i>
                      </div>
                      <div class="col-8">
                        <h2 class="socialText"> <%= @artist.instagram_num %> </h2>
                      </div>
                    </div>
                     </div>

                            <!-- twitter -->
                <div class="oneSocial twitter">
                    <div class="row">
                      <div class="col-4">
                         <i class="fab fa-twitter"></i>
                      </div>
                      <div class="col-8">
                        <h2 class="socialText"> <%= @artist.twitter_num %> </h2>
                      </div>
                    </div>
                     </div>
             <!-- END SOCIAL -->
             <div class="oneSocialInvert">
              <a href="<%= @artist.dropbox_link %>" target="_blank">            
                <button class="btn-download">
                  <h2><i class="fab fa-dropbox dropboxIcon"></i> Descarga</h2>
                </button>
              </a>
                 </div>
         
            
              </div>
          <!-- CARD END -->
     </div> 
            <!-- START COLUMN 2 -->
            
            <div class="col-sm-12 col-md-5 col-lg-5">
                <div id="video" class="">
                    <div id="video">
                      <iframe width="100%" height="100%" src="https://www.youtube.com/embed/<%= @artist.video_emb %>?controls=0" frameborder="0" allow="accelerometer; autoplay; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>
                      </div>
                    </div>
                    <hr>
            <h1 class="bioSec">Biography</h1>
            <p class="bio bioSec mb-3">
                <%= @artist.biography %>
            </p>
          
                    
              <div id="waveform" class="mb-3"></div>
              <div class="controls">
                  <button class="btn btn-warning" data-action="play">
                      <i class="far fa-play-circle"></i>
                      Escuchar
                      /
                      <i class="far fa-pause-circle"></i>
                      Parar
                  </button>
              </div>
              <hr>
              <p class="bioSec">CONTRATACIONES<br>
                <i class="fas fa-mobile-alt"></i> <%= @artist.booking %>
              </p>
          
            </div>
            <div class="col"></div>
            <!-- CLOSING 2 ROW DIV -->
          </div>
          <!-- START ONESHEET FOOTER -->
    <div class="row oneFooter mt-3 mb-3">
    <div class="col-1"></div>
        <div class="col-2">
        <a href="<%= @artist.spotify_link %>" target="_blank">
        <i class="fab fa-spotify fa-fw"></i>
        </a>
        </div>
        <div class="col-2">
        <a href="<%= @artist.facebook_link %>" target="_blank">
        <i class="fab fa-facebook-f fa-fw"></i>
        </a>

        </div>
        <div class="col-2">
        <a href="<%= @artist.instagram_link %>" target="_blank">
        <i class="fab fa-instagram fa-fw"></i> 
        </a>
        </div>
        <div class="col-2">
        <a href="<%= @artist.twitter_link %>" target="_blank">
        <i class="fab fa-twitter fa-fw"></i>
        </a>
        </div>
        <div class="col-2">
        <a href="<%= @artist.youtube_link %>" target="_blank">
        <i class="fab fa-youtube fa-fw"></i> 
        </a>
        </div>
    <div class="col-1"></div>
    </div>
    </div>

<button type="button" class="btn" data-toggle="modal" data-target="#adminModal">
.
</button>   

<!-- Modal -->
<div class="modal fade" id="adminModal" tabindex="-1" role="dialog" aria-labelledby="adminModalTitle" aria-hidden="true">
  <div class="modal-dialog modal-dialog-centered" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title" id="adminModalTitle">Modal title</h5>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
      <div class="modal-body">
         <%= link_to 'Edit Artist', edit_artist_path(@artist) %>  | <%= link_to 'Remove sheet', @artist,  method: :delete %> 
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
        <button type="button" class="btn btn-primary">Save changes</button>
      </div>
    </div>
  </div>
</div>

<script src="https://unpkg.com/wavesurfer.js"></script>
<script> 
console.log('All for Jesus')

var wavesurfer = WaveSurfer.create({
    container: '#waveform',
    waveColor: '#EEE9C3',
    progressColor: 'gold'

});

wavesurfer.load('<%= @artist.audio %>');

wavesurfer.on('ready', function () {
    wavesurfer.pause(); 
    wavesurfer.setVolume(0.5);
    // wavesurfer.toggleMute();
});

document
        .querySelector('[data-action="play"]')
        .addEventListener('click', wavesurfer.playPause.bind(wavesurfer));
</script>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Lnza.me</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
      <link href="https://lnza.me/favicon.jpg" rel="shortcut icon"/>
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.8.1/css/all.css" integrity="sha384-50oBUHEmvpQ+1lW4y57PTFmhCaXp0ML5d60M1M7uH2+nqUivzIebhndOJK28anvf" crossorigin="anonymous">
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
  </head>

  <body>
    <%= yield %>
  </body>


    <script src="https://unpkg.com/wavesurfer.js"></script>
    <script src="text.js"></script>
  <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>
</html>